# Generated by Django 3.2.14 on 2022-07-12 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meps', '0006_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 14, 46, 7, 562472, tzinfo=utc)),
        ),
    ]
